version: "3"

services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=group_blog
      - MYSQL_USER=group_blog
      - MYSQL_PASSWORD=grouppass
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    volumes:
      - ./server/src/main/resources/static/mysql:/var/lib/mysql