site:
  site-title: XiyouLinuxGroup群博
  site-sub-title: Free Open Share
  avatar-url: /images/logo.png
  is-in-author: false
  author-schema:
    author: XiyouLinuxGroup
    signature: "<i class='fa fa-map-marker' aria-hidden='true'> 东区逸夫楼 FZ103</i>"
  side-bar-links:
    index-url: /
    about-url: /about
    tag-url: /tag
    category-url: /category
    archive-url: /archive
    search-url: /search
  friend-links:
    - desc: 小组官网
      link: https://www.xiyoulinux.com/
      icon-class: fa fa-fw fa-chrome
    - desc: 邮件列表
      link: https://groups.google.com/forum/#!forum/xiyoulinux
      icon-class: fa fa-fw fa-envelope
